CREATE DATABASE Rojo_App; 
GO

USE Rojo_App;
GO

--------------------------------- DDL ---------------------------------

CREATE TABLE tipoUsuario
(
	IDTipoUsuario INT PRIMARY KEY IDENTITY,
	PerfisDeUsuario VARCHAR(150) NOT NULL
);
GO

CREATE TABLE Cor
(
	IDCor INT PRIMARY KEY IDENTITY,
	NomeCor VARCHAR (7)
);
GO

CREATE TABLE Empresa
(
	IDEmpresa INT PRIMARY KEY IDENTITY,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	Email VARCHAR (100) UNIQUE NOT NULL,
	Senha VARCHAR (50) NOT NULL,
	NomeFantasia VARCHAR (50) UNIQUE NOT NULL,
	RazaoSocial VARCHAR (50) UNIQUE NOT NULL,
	FundaçãoAniversario Date UNIQUE NOT NULL,
	Endereço VARCHAR (50) UNIQUE NOT NULL,
	Telefone VARCHAR (11) UNIQUE NOT NULL,
	TotalFuncionarios INT UNIQUE NOT NULL
);
GO

CREATE TABLE CorEmpresa
(
	IDEmpresa INT FOREIGN KEY REFERENCES Empresa(IDEmpresa),
	IDCor INT FOREIGN KEY REFERENCES Cor(IDCor),
);
GO

CREATE TABLE Usuario
(
		IDUsuario INT PRIMARY KEY IDENTITY,
		IDTipoUsuario INT FOREIGN KEY REFERENCES tipoUsuario(IDTipoUsuario),
		IDEmpresa INT FOREIGN KEY REFERENCES Empresa(IDEmpresa),
		Email VARCHAR (100) UNIQUE NOT NULL,
		Senha VARCHAR (50) NOT NULL,
		NomeUsu VARCHAR (50) NOT NULL,
		ImagemUsuario VARCHAR (300) NOT NULL,
);
GO	

CREATE TABLE Evento
(
		IDEvento INT PRIMARY KEY IDENTITY,
		IDEmpresa INT FOREIGN KEY REFERENCES Empresa(IDEmpresa),
		IDUsuario INT FOREIGN KEY REFERENCES Usuario (IDUsuario),
		NomeEvento VARCHAR (50) NOT NULL,
		Comentario VARCHAR (500) UNIQUE NOT NULL,
		DataEventoIncio DATETIME UNIQUE NOT NULL,
		DataEventoFim DATETIME UNIQUE NOT NULL,

);
GO

